### ISSUE TITLE
Spring Cloud Gateway Authentication

### ISSUE THREAD

**Issue by Dragonphy** [dromara/sureness#117]
**Is your feature request related to a problem? Please describe.**
I want to use database to authentication at the gateway. I followed [sample-tom](https://github.com/dromara/sureness/tree/master/sample-tom/src/main/java/com/usthe/sureness/sample/tom) and [spring-webflux-sureness](https://github.com/dromara/sureness/tree/master/samples/spring-webflux-sureness). 
* SurenessConfiguration
```java
@Configuration
public class SurenessConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(SurenessConfiguration.class);

    @Bean
    ProcessorManager processorManager(SurenessAccountProvider accountProvider) {
        if (logger.isDebugEnabled()) {
            logger.debug("DefaultProcessorManager init");
        }
        return new DefaultProcessorManager(Arrays.asList(new JwtProcessor()));
    }

    /**
     * @param databasePathTreeProvider the path tree resource load from database
     */
    @Bean
    TreePathRoleMatcher pathRoleMatcher(PathTreeProvider databasePathTreeProvider) {
        // pathRoleMatcher init
        DefaultPathRoleMatcher pathRoleMatcher = new DefaultPathRoleMatcher();
        pathRoleMatcher.setPathTreeProvider(databasePathTreeProvider);
        pathRoleMatcher.buildTree();
        if (logger.isDebugEnabled()) {
            logger.debug("DefaultPathRoleMatcher init");
        }
        return pathRoleMatcher;
    }

    @Bean
    SubjectFactory subjectFactory() {
        // SubjectFactory init
        SubjectFactory subjectFactory = new SurenessSubjectFactory();
        subjectFactory.registerSubjectCreator(Arrays.asList(new JwtSubjectReactiveCreator()));
        return subjectFactory;
    }

    /**
     * surenessSecurityManager init
     */
    @Bean
    SurenessSecurityManager securityManager(ProcessorManager processorManager,
                                            TreePathRoleMatcher pathRoleMatcher, SubjectFactory subjectFactory) {
        SurenessSecurityManager securityManager = SurenessSecurityManager.getInstance();
        securityManager.setPathRoleMatcher(pathRoleMatcher);
        securityManager.setSubjectFactory(subjectFactory);
        securityManager.setProcessorManager(processorManager);
        if (logger.isDebugEnabled()) {
            logger.debug("SurenessSecurityManager init");
        }
        return securityManager;
    }
}
````
* application.yml
```yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.252:8848
    gateway:
      default-filters:
        - SurenessAuth
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
```
An error occurred when I requested `http://localhost:8083/auth/token`.
```
com.usthe.sureness.processor.exception.UnsupportedSubjectException: this request can not create subject by creators,please config no subject creator by default
	at com.usthe.sureness.mgt.SurenessSecurityManager.checkIn(SurenessSecurityManager.java:72) ~[sureness-core-1.0.3.jar:na]
	at com.zetacn.zetagateway.sureness.filter.SurenessFilter.filter(SurenessFilter.java:38) ~[classes/:na]
```

**Comment by tomsun28** [comment]
Hi, noSubjectCreator  is must need for creating NoneSubject when the request does not carry  any auth information  
````
        subjectFactory.registerSubjectCreator(Arrays.asList(
                // attention! must add noSubjectCreator first
                new NoneSubjectReactiveCreator(),
                new JwtSubjectReactiveCreator());
````
